// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Demo$Reasonml = require("../src/Demo.bs.js");

Jest.describe("Token", (function (param) {
        return Jest.test("lookupIdentifier", (function (param) {
                      return Jest.Expect.toEqual(/* tuple */[
                                  /* FUNCTION */22,
                                  /* LET */23,
                                  /* IDENT */Block.__(1, ["random_identifier"])
                                ], Jest.Expect.expect(/* tuple */[
                                      Demo$Reasonml.Token.lookupIdentifier("fn"),
                                      Demo$Reasonml.Token.lookupIdentifier("let"),
                                      Demo$Reasonml.Token.lookupIdentifier("random_identifier")
                                    ]));
                    }));
      }));

Jest.describe("Lexer", (function (param) {
        return Jest.describe("nextToken", (function (param) {
                      var gatherTokens = function (input) {
                        var lexer = Demo$Reasonml.Lexer.make(/* String */[input]);
                        var chars = input.split("");
                        return chars.reduce((function (param, param$1) {
                                        var tokens = param[1];
                                        var match = Demo$Reasonml.Lexer.nextToken(param[0]);
                                        var token = match[1];
                                        var l = match[0];
                                        if (token === /* EOF */0) {
                                          return /* tuple */[
                                                  l,
                                                  tokens
                                                ];
                                        } else {
                                          return /* tuple */[
                                                  l,
                                                  $$Array.concat(/* :: */[
                                                        tokens,
                                                        /* :: */[
                                                          [token],
                                                          /* [] */0
                                                        ]
                                                      ])
                                                ];
                                        }
                                      }), /* tuple */[
                                      lexer,
                                      []
                                    ])[1];
                      };
                      Jest.test("simple", (function (param) {
                              return Jest.Expect.toEqual([
                                          /* ASSIGN */1,
                                          /* PLUS */2,
                                          /* LPAREN */13,
                                          /* RPAREN */14,
                                          /* LBRACE */15,
                                          /* RBRACE */16,
                                          /* COMMA */11,
                                          /* SEMICOLON */12,
                                          /* ILLEGAL */Block.__(0, ["|"]),
                                          /* BANG */4,
                                          /* MINUS */3,
                                          /* SLASH */6,
                                          /* ASTERISK */5,
                                          /* LT */7,
                                          /* GT */8
                                        ], Jest.Expect.expect(gatherTokens("=+(){},;|!-/*<>")));
                            }));
                      return Jest.test("multi-line", (function (param) {
                                    return Jest.Expect.toEqual([
                                                /* LET */23,
                                                /* IDENT */Block.__(1, ["five"]),
                                                /* ASSIGN */1,
                                                /* INTEGER */Block.__(2, [5]),
                                                /* SEMICOLON */12,
                                                /* LET */23,
                                                /* IDENT */Block.__(1, ["ten"]),
                                                /* ASSIGN */1,
                                                /* INTEGER */Block.__(2, [10]),
                                                /* SEMICOLON */12,
                                                /* LET */23,
                                                /* IDENT */Block.__(1, ["add"]),
                                                /* ASSIGN */1,
                                                /* FUNCTION */22,
                                                /* LPAREN */13,
                                                /* IDENT */Block.__(1, ["x"]),
                                                /* COMMA */11,
                                                /* IDENT */Block.__(1, ["y"]),
                                                /* RPAREN */14,
                                                /* LBRACE */15,
                                                /* IDENT */Block.__(1, ["x"]),
                                                /* PLUS */2,
                                                /* IDENT */Block.__(1, ["y"]),
                                                /* SEMICOLON */12,
                                                /* RBRACE */16,
                                                /* SEMICOLON */12,
                                                /* IF */19,
                                                /* LPAREN */13,
                                                /* IDENT */Block.__(1, ["add"]),
                                                /* LPAREN */13,
                                                /* IDENT */Block.__(1, ["five"]),
                                                /* COMMA */11,
                                                /* IDENT */Block.__(1, ["ten"]),
                                                /* RPAREN */14,
                                                /* GT */8,
                                                /* INTEGER */Block.__(2, [5]),
                                                /* RPAREN */14,
                                                /* LBRACE */15,
                                                /* RETURN */21,
                                                /* TRUE */17,
                                                /* SEMICOLON */12,
                                                /* RBRACE */16,
                                                /* ELSE */20,
                                                /* LBRACE */15,
                                                /* RETURN */21,
                                                /* FALSE */18,
                                                /* SEMICOLON */12,
                                                /* RBRACE */16,
                                                /* INTEGER */Block.__(2, [10]),
                                                /* EQ */9,
                                                /* INTEGER */Block.__(2, [10]),
                                                /* SEMICOLON */12,
                                                /* INTEGER */Block.__(2, [9]),
                                                /* NOT_EQ */10,
                                                /* INTEGER */Block.__(2, [10]),
                                                /* SEMICOLON */12
                                              ], Jest.Expect.expect(gatherTokens("\r\n        let five = 5;\r\n        let ten = 10;\r\n\r\n        let add = fn   (x, y) {\r\n          x + y;\r\n        };\r\n\r\n        if (add(five, ten) > 5) {\r\n          return true;\r\n        } else {\r\n          return false;\r\n        }\r\n\r\n        10 == 10;\r\n        9 != 10;\r\n        ")));
                                  }));
                    }));
      }));

/*  Not a pure module */
